-- This SQL script update an replace oag urls so you can develop your computer with production database dump
UPDATE oskari_maplayer SET url='http://livigeot-vip.vally.local/inspirepalvelu/wms' WHERE url='http://oag.liikennevirasto.fi/inspirepalvelu/wms';
UPDATE oskari_maplayer SET url='http://livigeot-vip.vally.local/inspirepalvelu/rajaus_aineistot/wms' WHERE url='http://oag.liikennevirasto.fi/inspirepalvelu/rajaus_aineistot/wms';
UPDATE oskari_maplayer SET url='http://livirast-vip.vally.local/rasteripalvelu/wmts' WHERE url='http://oag.liikennevirasto.fi/rasteripalvelu/wmts';
UPDATE oskari_maplayer SET url='http://livirast-vip.vally.local/rasteripalvelu-mml/wmts/maasto/1.0.0/maastokartta/' WHERE url='http://oag.liikennevirasto.fi/rasteripalvelu-mml/wmts/maasto/1.0.0/maastokartta/';
UPDATE oskari_maplayer SET options= REPLACE(options, 'http://oag.liikennevirasto.fi/rasteripalvelu-mml/wmts/maasto/1.0.0', 'http://livirast-vip.vally.local/rasteripalvelu-mml/wmts/maasto/1.0.0') WHERE options LIKE '%http://oag.liikennevirasto.fi/rasteripalvelu-mml/wmts/maasto/1.0.0%';
UPDATE oskari_maplayer SET options= REPLACE(options, 'https://oag.liikennevirasto.fi/rasteripalvelu-mml/wmts/maasto/1.0.0', 'http://livirast-vip.vally.local/rasteripalvelu-mml/wmts/maasto/1.0.0') WHERE options LIKE '%https://oag.liikennevirasto.fi/rasteripalvelu-mml/wmts/maasto/1.0.0%';
UPDATE oskari_resource SET resource_mapping = REPLACE(resource_mapping, 'http://oag.liikennevirasto.fi/inspirepalvelu/wms', 'http://livigeot-vip.vally.local/inspirepalvelu/wms');
UPDATE oskari_resource SET resource_mapping = REPLACE(resource_mapping, 'http://oag.liikennevirasto.fi/inspirepalvelu/rajaus_aineistot/wms', 'http://livigeot-vip.vally.local/inspirepalvelu/rajaus_aineistot/wms');
UPDATE oskari_resource SET resource_mapping = REPLACE(resource_mapping, 'http://oag.liikennevirasto.fi/rasteripalvelu/wmts', 'http://livirast-vip.vally.local/rasteripalvelu/wmts');
UPDATE oskari_resource SET resource_mapping = REPLACE(resource_mapping, 'http://oag.liikennevirasto.fi/rasteripalvelu-mml/wmts/maasto/1.0.0/maastokartta/', 'http://livirast-vip.vally.local/rasteripalvelu-mml/wmts/maasto/1.0.0/maastokartta/');